"""Edit pet_achievement

Revision ID: 8a882a3c6c8b
Revises: 2caeaee08e0a
Create Date: 2024-10-18 19:42:07.616155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a882a3c6c8b'
down_revision: Union[str, None] = '2caeaee08e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PetAchievement')
    op.create_unique_constraint(None, 'achievements', ['id'])
    op.create_unique_constraint(None, 'pets', ['id'])
    op.create_unique_constraint(None, 'stats', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'stats', type_='unique')
    op.drop_constraint(None, 'pets', type_='unique')
    op.drop_constraint(None, 'achievements', type_='unique')
    op.create_table('PetAchievement',
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name='PetAchievement_achievement_id_fkey'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='PetAchievement_pet_id_fkey')
    )
    op.drop_table('pet_achievements')
    # ### end Alembic commands ###
